version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - compliance-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./admin_password:/etc/grafana/admin_password:ro
      - ./provisioning:/etc/grafana/provisioning:ro
      - ../dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - compliance-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - compliance-net

  compliance-monitor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.compliance-monitor
    container_name: compliance-monitor
    environment:
      - PROMETHEUS_PORT=8000
      - LOG_LEVEL=INFO
      - HEALTH_CHECK_CONFIG=/app/config/health_config.json
    volumes:
      - ../scripts:/app/scripts:ro
      - ../sre/health-checks/health_config.json:/app/config/health_config.json:ro
    command: ["python3", "/app/scripts/compliance-metrics.py"]
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - elasticsearch
      - alertmanager
    networks:
      - compliance-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--cluster.advertise-address=0.0.0.0:9093'
    networks:
      - compliance-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - compliance-net
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  es_data:
  alertmanager_data:

networks:
  compliance-net:
    driver: bridge 